# Generated by Django 3.1.7 on 2021-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopdata',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=50)),
                ('shopimage', models.CharField(max_length=50)),
                ('shopdesc', models.CharField(max_length=50)),
                ('shopcontact', models.CharField(max_length=100)),
                ('shopemail', models.CharField(max_length=50)),
                ('shopaddress', models.CharField(max_length=100)),
                ('shoparea', models.CharField(max_length=50)),
                ('shopcity', models.CharField(max_length=50)),
                ('shopdistrict', models.CharField(max_length=50)),
                ('shopstate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
