# Generated by Django 3.1.7 on 2021-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdata',
            name='holiday',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopdata',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='sid',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
