# Generated by Django 3.1.7 on 2021-03-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0003_auto_20210311_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='country',
            new_name='state',
        ),
    ]
