# Generated by Django 3.1.7 on 2021-03-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0004_auto_20210311_1300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
