# Generated by Django 3.1.7 on 2021-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0005_auto_20210311_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('itemcategory', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
