# Generated by Django 3.1.7 on 2021-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdata',
            name='password',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopdata',
            name='username',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
