# Generated by Django 3.1.7 on 2021-03-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0007_auto_20210311_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopdata',
            table='shopdata',
        ),
    ]
