# Generated by Django 3.1.7 on 2021-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0010_auto_20210315_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='shopaddress',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='shopname',
            field=models.CharField(max_length=200),
        ),
    ]
