# Generated by Django 3.1.7 on 2021-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplocatingapp', '0012_auto_20210424_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='shopdesc',
            field=models.CharField(max_length=300),
        ),
    ]
