/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.eclipse.persistence.jpa.jpql.ExpressionTools;

/**
 *
 * @author win 07
 */
public class addnewbooks extends javax.swing.JDialog {

    /**
     * Creates new form addnewbooks
     */
    public addnewbooks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 400, 90, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("rack no");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(89, 356, 62, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(248, 89, 289, 26);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(248, 265, 289, 26);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(248, 221, 289, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("author");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(89, 268, 46, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(248, 177, 289, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("book for stream");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(89, 224, 113, 20);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(248, 309, 289, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("book name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(89, 180, 79, 20);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(248, 353, 289, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("publication");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(89, 312, 77, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("book no");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(89, 136, 58, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add new Books");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(89, 20, 448, 58);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(248, 133, 289, 26);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("new id");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(170, 400, 100, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(89, 92, 13, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(400, 400, 90, 29);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(510, 400, 90, 29);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton5.setText("new book no");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 400, 140, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/images/add new books.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 620, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText())|| "".equals(jTextField3.getText())|| "".equals(jTextField4.getText()) || "".equals(jTextField5.getText()) || "".equals(jTextField6.getText())|| "".equals(jTextField7.getText()))
{
    JOptionPane.showMessageDialog(this, "please fill up all data in the fields  ", "empty field" ,JOptionPane.ERROR_MESSAGE);
}
else{ 
    try{
                Class.forName("org.sqlite.JDBC");
                Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
                Statement  stmt = c.createStatement();
                String sql = ("insert into books3 (id,bookno,name,bookstream,author,publication,rack)values"
                          + "("+Integer.parseInt(jTextField1.getText())+","+Integer.parseInt(jTextField2.
                                  getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.
                                          getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"');");              
                stmt.executeUpdate(sql);
                 sql = ("insert into books (id,bookno,name,bookstream,author,publication,rack)values("+Integer.parseInt(jTextField1.getText())+","+Integer.parseInt(jTextField2.getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"');");
               
                stmt.executeUpdate(sql);
             
               try{
                sql = ("insert into books2 (id,bookno,name,bookstream,author,publication,rack)values"
                          + "("+Integer.parseInt(jTextField1.getText())+","+Integer.parseInt(jTextField2.
                                  getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.
                                          getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"');");              
                stmt.executeUpdate(sql);
               }catch(Exception e)
               {}
               
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
    }
               catch(ClassNotFoundException  e )
               { 
                   e.printStackTrace();
                 }
                 catch( NumberFormatException e )
               { 
                   e.printStackTrace();
                   JOptionPane.showMessageDialog(this, "you had entered string in place of numbers", "number error" ,JOptionPane.ERROR_MESSAGE);
             } 
     catch(SQLException e )
               { 
                   JOptionPane.showMessageDialog(this, "Already this bookno is entered  ", "already entered" ,JOptionPane.ERROR_MESSAGE);
                   e.printStackTrace();
                  
                }
               
   
} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jTextField1.setEnabled(false);
        if("".equals(jTextField1.getText()))
        {
            jTextField2.setText("");
               jTextField3.setText(""); 
               jTextField4.setText("");
               jTextField5.setText("");
               jTextField6.setText("");
               jTextField7.setText("");
        }
        else{
        
        try {
            Class.forName("org.sqlite.JDBC");
            Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
            Statement  stmt = c.createStatement();
            ResultSet rs=stmt.executeQuery("select * from books2");  
            try{
               int f=Integer.parseInt(jTextField1.getText());
              
            while(rs.next())
            {
           if(rs.getInt(1)==f)
           {
               jTextField3.setText(rs.getString(3));
               jTextField4.setText(rs.getString(4));
                jTextField5.setText(rs.getString(5));
                 jTextField6.setText(rs.getString(6));
                  jTextField7.setText(rs.getString(7));
                 
               break;
           }
           else
           {
               jTextField2.setText("");
               jTextField3.setText("");
               jTextField4.setText("");
               jTextField5.setText("");
               jTextField6.setText("");
               jTextField7.setText("");
               
           }
           
          
            }
             rs.close();
           stmt.close();
                c.close();
                    
            }
catch(Exception e)
{e.printStackTrace();}// TODO add your handling ode here:
        } catch (SQLException | ClassNotFoundException ex) {
        ex.printStackTrace();
        }
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
 if(evt.getKeyCode() == KeyEvent.VK_ENTER )     {
               
     jButton1ActionPerformed(null);

 }   
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                jTextField1.setEnabled(true);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER )
         {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
         }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER )
         {
             this.dispose();
         }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setEnabled(false);
        try{ 
        Class.forName("org.sqlite.JDBC");
            Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
            Statement  stmt = c.createStatement();
            ResultSet gs=stmt.executeQuery("select * from books2");  
            int count=0;
            while(gs.next())
            {
                count++;
            }
            gs.close();                  
            ResultSet rs=stmt.executeQuery("select * from books2");  
              int arr[]={} ;
              int ci=0;
              int i =0;
              for( i=1;i<=count+1;i++)
             {
                 while(rs.next())
                 {
                    if(rs.getInt(1)==i)
                    {
                        ci=i;
                        break;
                    }
                 }
                 if(ci!=i)
                 {
                     jTextField1.setText(Integer.toString(i));
                      
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                     break;
                 }
             }       
         rs.close();
         stmt.close();
         c.close();         
       }
            catch(Exception e )
                    {e.printStackTrace();}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{ 
        Class.forName("org.sqlite.JDBC");
            Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
            Statement  stmt = c.createStatement();
            ResultSet gs=stmt.executeQuery("select * from books3");  
            int count=0;
            while(gs.next())
            {
                count++;
            }
            gs.close();                  
            ResultSet rs=stmt.executeQuery("select * from books3");  
              int arr[]={} ;
              int ci=0;
              int i =0;
              for( i=1;i<=count+1;i++)
             {
                 while(rs.next())
                 {
                    if(rs.getInt(2)==i)
                    {
                        ci=i;
                        break;
                    }
                 }
                 if(ci!=i)
                 {
                        
                      jTextField2.setText(Integer.toString(i));
                     break;
                 }
             }       
         rs.close();
         stmt.close();
         c.close();         
       }
            catch(Exception e )
                    {e.printStackTrace();}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewbooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addnewbooks dialog = new addnewbooks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
