/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagement;

import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author win 07
 */
public class issuebooks extends javax.swing.JDialog {

    /**
     * Creates new form deletebooks
     */
    public issuebooks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search.setToolTipText("search");
        jPanel1.add(search);
        search.setBounds(0, 60, 210, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 60, 46, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 250, 316, 26);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(190, 290, 316, 26);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(190, 330, 316, 26);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(190, 370, 316, 26);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(190, 408, 316, 26);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(190, 445, 316, 26);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(190, 489, 316, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 250, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Book no");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 290, 58, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Books name ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 330, 91, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("stream");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 370, 48, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("author");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 408, 46, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("publicaton");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 448, 73, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 540, 120, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("rack");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 492, 29, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Issue books");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1190, 58);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(750, 250, 322, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("student id");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 250, 70, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("student name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(577, 287, 96, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("class");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(577, 331, 33, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("mobile no");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(577, 375, 71, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("libray card no");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(577, 419, 97, 20);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(751, 284, 322, 26);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(751, 328, 322, 26);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField11);
        jTextField11.setBounds(751, 372, 322, 26);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField12);
        jTextField12.setBounds(751, 416, 322, 26);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("issue books");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 540, 220, 29);

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table1.setName(""); // NOI18N
        table1.getTableHeader().setResizingAllowed(false);
        table1.getTableHeader().setReorderingAllowed(false);
        table1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table1FocusGained(evt);
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 1190, 121);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("search ");
        jPanel1.add(jButton3);
        jButton3.setBounds(1090, 250, 83, 29);

        jLabel16.setText("note : you have to enter student id to get student profile");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(580, 474, 330, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/images/issue books.jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 0, 1190, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   public void tablecreation()
{
          try{
    
    Class.forName("org.sqlite.JDBC");
                Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
          Statement  stmt = c.createStatement();
            ResultSet rs=stmt.executeQuery("select * from books ;");
            
            int q=0;
            while(rs.next())
            {
                q++;
            }
            rs.close();
            
        Object[][] data = new Object[q][7]; 
      
    ResultSet gs=stmt.executeQuery("select * from books order by id asc ;");

    int i=0;
   
    while(gs.next())
    {
        
        data[i][0]= rs.getInt(1);
        data[i][1]=rs.getInt(2);
        data[i][2]=rs.getString(3);
        data[i][3]=rs.getString(4);
        data[i][4]=rs.getString(5);
        data[i][5]=rs.getString(6);
        data[i][6]=rs.getString(7);
   i++;
    }
         String column[] = {"id", "Book no", "Books name", "stream", "author", "publicaton", "rack"};
         DefaultTableModel md = new DefaultTableModel(data, column)
    {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
     
    };
        table1.setModel(md);
        
         DefaultTableCellRenderer cell = new DefaultTableCellRenderer();
    cell.setHorizontalAlignment(SwingConstants.CENTER);
        this.table1.getColumn("id").setCellRenderer(cell);
        this.table1.getColumn("Book no").setCellRenderer(cell);
       this.table1.getColumn("Books name").setCellRenderer(cell);
        this.table1.getColumn("stream").setCellRenderer(cell);
        this.table1.getColumn("author").setCellRenderer(cell);
        this.table1.getColumn("publicaton").setCellRenderer(cell);
        this.table1.getColumn("rack").setCellRenderer(cell);
        this.table1.setRowHeight(30);
        table1.setFont(new Font("",0,16));
        table1.setColumnSelectionAllowed(false);
        table1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table1.getTableHeader().setDefaultRenderer(cell);
        table1.setShowGrid(true);
        gs.close();
        stmt.close();
        c.close();
        
  
         TableRowSorter sorter = new TableRowSorter(md);
        
        table1.setRowSorter(sorter);
     sorter.setComparator(0, new IntComparator());
         sorter.setComparator(1, new IntComparator());
         table1.getTableHeader().setReorderingAllowed(false);
        search.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = search.getText();

                if (text.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = search.getText();

                if (text.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            


        });
        
        table1.putClientProperty("terminateEditOnFocusLost", true);
   
        }
        catch(Exception e){e.printStackTrace();}
  
}
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
      
      
        try{
         tablecreation();
        }catch(Exception e ){e.printStackTrace();}
    }//GEN-LAST:event_formWindowOpened

    private void table1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table1FocusGained
       
    }//GEN-LAST:event_table1FocusGained

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
 int row = table1.getSelectedRow(); int col = 0;
    String str =String.valueOf(table1.getValueAt(row,col));
        jTextField1.setText(str);
         row = table1.getSelectedRow();  col = 1;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField2.setText(str);
        row = table1.getSelectedRow();  col = 2;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField3.setText(str);
        row = table1.getSelectedRow();  col = 3;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField4.setText(str);
        row = table1.getSelectedRow();  col = 4;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField5.setText(str);
        row = table1.getSelectedRow();  col = 5;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField6.setText(str);
        row = table1.getSelectedRow();  col = 6;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField7.setText(str);
        
    }//GEN-LAST:event_table1MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER )
         {
             this.dispose();
         }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
       if("".equals(jTextField8.getText()))
       {
                        jTextField9.setText("");
                        jTextField10.setText("");
                        jTextField11.setText("");
                        jTextField12.setText("");
       }
        try{
            Class.forName("org.sqlite.JDBC");
            Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
            Statement  stmt = c.createStatement();
            ResultSet rs=stmt.executeQuery("select * from students");
            try{
                int f=Integer.parseInt(jTextField8.getText());
                System.out.println(f);
                while(rs.next())
                {
                    if(rs.getInt(1)==f)
                    {
                        jTextField9.setText(rs.getString(2));
                        jTextField10.setText(rs.getString(3));
                        jTextField11.setText(rs.getString(4));
                        jTextField12.setText(rs.getString(5));

                        break;
                    }
                    else
                    {
                        jTextField9.setText("");
                        jTextField10.setText("");
                        jTextField11.setText("");
                        jTextField12.setText("");

                    }

                }
                rs.close();
                stmt.close();
                c.close();

            }
            catch(Exception e)
            {}// TODO add your handling ode here:
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(jTextField1.getText()) || "".equals(jTextField2.getText())|| "".equals(jTextField3.getText())
        || "".equals(jTextField4.getText()) || "".equals(jTextField5.getText()) || "".equals(jTextField6.getText())
        || "".equals(jTextField7.getText())  || "".equals(jTextField8.getText())  || "".equals(jTextField9.getText())
                 || "".equals(jTextField10.getText())  || "".equals(jTextField11.getText())  || "".equals(jTextField12.getText()))
{
    JOptionPane.showMessageDialog(this, "please fill up all data in the fields  ", "empty field" ,JOptionPane.ERROR_MESSAGE);
}
        
        
        try{        
               BigInteger p = new BigInteger(jTextField11.getText());
             
              
                Class.forName("org.sqlite.JDBC");
                Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
                Statement  stmt = c.createStatement();
                String sql = ("insert into issue (studentid,studentname,std,contact,librarycardno,id,bookno,name,bookstream,"
                        + "author,publication,rack)values("+Integer.parseInt(jTextField8.getText())+",'"+jTextField9.getText()+"','"+jTextField10.getText()+"','"+
                        jTextField11.getText()+"',"+Integer.parseInt(jTextField12.getText())+","+Integer.parseInt(jTextField1.getText())
                        +","+Integer.parseInt(jTextField2.getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()
                        +"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"');");
              stmt.executeUpdate(sql);
              DateFormat df = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss aa");
        Date d = new Date();
        
     sql = ("insert into isrthi (studentid,studentname,std,contact,librarycardno,id,bookno,name,bookstream,"
            + "author,publication,rack,issue,date)values("+Integer.parseInt(jTextField8.getText())+",'"+jTextField9.getText()+"','"+jTextField10.getText()+"','"+
      jTextField11.getText()+"',"+Integer.parseInt(jTextField12.getText())+","+Integer.parseInt(jTextField1.getText())
 +","+Integer.parseInt(jTextField2.getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()
   +"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"','issued','"+df.format(d)+"');");
              stmt.executeUpdate(sql);
       sql = ("insert into history (studentid,studentname,std,contact,librarycardno,id,bookno,name,bookstream,"
            + "author,publication,rack,date)values("+Integer.parseInt(jTextField8.getText())+",'"+jTextField9.getText()+"','"+jTextField10.getText()+"','"+
      jTextField11.getText()+"',"+Integer.parseInt(jTextField12.getText())+","+Integer.parseInt(jTextField1.getText())
 +","+Integer.parseInt(jTextField2.getText())+",'"+jTextField3.getText()+"','"+jTextField4.getText()
   +"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"','"+df.format(d)+"');");
              stmt.executeUpdate(sql);
                
                
                try{
             Connection ct=DriverManager.getConnection("jdbc:sqlite:books1.db");
                                  stmt = ct.createStatement();
                                PreparedStatement ps = ct.prepareStatement("delete from books where bookno = "+jTextField2.getText()+";");
                                ps.executeUpdate();
           }
           catch(Exception e)
           {
               e.printStackTrace();
           }           
        Thread t = new Thread() {
 
            @Override
            public void run() {
                 remove(table1);
                 JTable table1 = new JTable();
        jScrollPane2.add(table1);
        tablecreation();
            }
        };
        t.start();
                
                
                
                
                
               
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                stmt.close();
                c.close();
    }
               catch(ClassNotFoundException  e )
               { 
                   e.printStackTrace();
                 }
                 catch( NumberFormatException e )
               { 
                   e.printStackTrace();
                  JOptionPane.showMessageDialog(this, "you had entered string in place of numbers or please check whether you had entered very large number in any box except mobile no", "number error" ,JOptionPane.ERROR_MESSAGE);
             }
                catch(SQLException e )
               { 
                   e.printStackTrace();
                   JOptionPane.showMessageDialog(this, "you had entered string in place of numbers or please check whether you had entered very large number in any box except mobile no", "number error" ,JOptionPane.ERROR_MESSAGE);
                }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void table1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyPressed
         
    }//GEN-LAST:event_table1KeyPressed

    private void table1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyReleased
        int row = table1.getSelectedRow(); int col = 0;
    String str =String.valueOf(table1.getValueAt(row,col));
        jTextField1.setText(str);
         row = table1.getSelectedRow();  col = 1;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField2.setText(str);
        row = table1.getSelectedRow();  col = 2;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField3.setText(str);
        row = table1.getSelectedRow();  col = 3;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField4.setText(str);
        row = table1.getSelectedRow();  col = 4;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField5.setText(str);
        row = table1.getSelectedRow();  col = 5;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField6.setText(str);
        row = table1.getSelectedRow();  col = 6;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField7.setText(str);
        
    }//GEN-LAST:event_table1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                issuebooks dialog = new issuebooks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
