/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagement;

import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author win 07
 */
public class viewissuereturndatehistory extends javax.swing.JDialog {

    /**
     * Creates new form deletebooks
     */
    public viewissuereturndatehistory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1261, 671));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        search.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        search.setToolTipText("search");
        jPanel1.add(search);
        search.setBounds(0, 60, 210, 26);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 590, 120, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Transaction History");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1190, 58);

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        table1.setName(""); // NOI18N
        table1.getTableHeader().setResizingAllowed(false);
        table1.getTableHeader().setReorderingAllowed(false);
        table1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table1FocusGained(evt);
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 1260, 121);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("student id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(620, 280, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("student name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 330, 96, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("class");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 370, 33, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("mobile no");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 420, 71, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("library card no");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(620, 460, 103, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("book id ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 280, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("book no");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 320, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 360, 39, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("stream ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 410, 53, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("author");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 450, 46, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("publication");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 500, 90, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("rack");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 540, 29, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(761, 279, 400, 26);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(761, 323, 400, 26);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(761, 367, 400, 26);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(761, 411, 400, 26);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(761, 452, 400, 26);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(158, 274, 400, 26);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(160, 320, 400, 26);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(158, 362, 400, 26);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField9);
        jTextField9.setBounds(158, 406, 400, 26);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField10);
        jTextField10.setBounds(158, 447, 400, 26);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField11);
        jTextField11.setBounds(158, 491, 400, 26);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField12);
        jTextField12.setBounds(158, 535, 400, 26);

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField13);
        jTextField13.setBounds(760, 500, 400, 26);

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(jTextField14);
        jTextField14.setBounds(760, 540, 400, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Date");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(620, 500, 110, 20);

        r.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        r.setText("Return date");
        jPanel1.add(r);
        r.setBounds(620, 540, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library/images/retun books.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 670);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1260, 669);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   public void tablecreation()
{
          try{
    
    Class.forName("org.sqlite.JDBC");
                Connection c=DriverManager.getConnection("jdbc:sqlite:books1.db");
          Statement  stmt = c.createStatement();
            ResultSet rs=stmt.executeQuery("select * from history ;");
            
            int q=0;
            while(rs.next())
            {
                q++;
            }
            rs.close();
            
        Object[][] data = new Object[q][14]; 
      
    ResultSet gs=stmt.executeQuery("select * from history ;");//order by id asc

    int i=0;
   
    while(gs.next())
    {
        
        data[i][0]= rs.getInt(1);
        data[i][1]=rs.getString(2);
        data[i][2]=rs.getString(3);
        data[i][3]=rs.getString(4);
        data[i][4]=rs.getString(5);
        data[i][5]=rs.getInt(6);
        data[i][6]=rs.getInt(7);
        data[i][7]=rs.getString(8);
        data[i][8]=rs.getString(9);
        data[i][9]=rs.getString(10);
        data[i][10]=rs.getString(11);
        data[i][11]=rs.getString(12);
        data[i][12]=rs.getString(13);
        data[i][13]=rs.getString(14);
    
        
   i++;
    }
         String column[] = {"Student id","Student name","class","mobile no","Library card no","id", 
             "Book no", "Books name", "stream", "author", "publicaton", "rack","issue date",
             "return date"};
         DefaultTableModel md = new DefaultTableModel(data, column)
    {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
     
    };
        table1.setModel(md);
        
         DefaultTableCellRenderer cell = new DefaultTableCellRenderer();
    cell.setHorizontalAlignment(SwingConstants.CENTER);
  this.table1.getColumn("Student id").setCellRenderer(cell);
  this.table1.getColumn("Student name").setCellRenderer(cell);   
   this.table1.getColumn("class").setCellRenderer(cell);  
   this.table1.getColumn("mobile no").setCellRenderer(cell);  
   this.table1.getColumn("Library card no").setCellRenderer(cell);  
        this.table1.getColumn("id").setCellRenderer(cell);
        this.table1.getColumn("Book no").setCellRenderer(cell);
       this.table1.getColumn("Books name").setCellRenderer(cell);
        this.table1.getColumn("stream").setCellRenderer(cell);
        this.table1.getColumn("author").setCellRenderer(cell);
        this.table1.getColumn("publicaton").setCellRenderer(cell);
        this.table1.getColumn("rack").setCellRenderer(cell);
        

        this.table1.getColumn("issue date").setCellRenderer(cell);
       
        this.table1.getColumn("return date").setCellRenderer(cell);
      
        
        this.table1.setRowHeight(30);
        table1.setFont(new Font("",0,16));
        table1.setColumnSelectionAllowed(false);
        table1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table1.getTableHeader().setDefaultRenderer(cell);
        table1.setShowGrid(true);
        gs.close();
        stmt.close();
        c.close();
        
        table1.getColumnModel().getColumn(9).setMinWidth(0);        // hide author column
   table1.getColumnModel().getColumn(9).setMaxWidth(0);     
   table1.getColumnModel().getColumn(9).setWidth(0);
  
   table1.getColumnModel().getColumn(10).setMinWidth(0);
   table1.getColumnModel().getColumn(10).setMaxWidth(0);//hide publication column
   table1.getColumnModel().getColumn(10).setWidth(0);
  
   
         TableRowSorter sorter = new TableRowSorter(md);
        
        table1.setRowSorter(sorter);
     sorter.setComparator(0, new IntComparator());
         sorter.setComparator(5, new IntComparator());
         sorter.setComparator(6, new IntComparator());
           
         table1.getTableHeader().setReorderingAllowed(false);
        search.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = search.getText();

                if (text.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text,6));
                    
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = search.getText();

                if (text.trim().length() == 0) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text,6));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            


        });
        
        table1.putClientProperty("terminateEditOnFocusLost", true);
   
        }
        catch(Exception e){e.printStackTrace();}
  
}
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
        try{
         tablecreation();
        }catch(Exception e ){e.printStackTrace();}
    }//GEN-LAST:event_formWindowOpened

    private void table1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table1FocusGained
       
    }//GEN-LAST:event_table1FocusGained

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
      int row = table1.getSelectedRow(); int col = 0;
    String str =String.valueOf(table1.getValueAt(row,col));
        jTextField1.setText(str);
         row = table1.getSelectedRow();  col = 1;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField2.setText(str);
        row = table1.getSelectedRow();  col = 2;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField3.setText(str);
        row = table1.getSelectedRow();  col = 3;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField4.setText(str);
        row = table1.getSelectedRow();  col = 4;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField5.setText(str);
        
    
    row = table1.getSelectedRow();   col = 5;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField6.setText(str);
         row = table1.getSelectedRow();  col = 6;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField7.setText(str);
        row = table1.getSelectedRow();  col = 7;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField8.setText(str);
        row = table1.getSelectedRow();  col = 8;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField9.setText(str);
        row = table1.getSelectedRow();  col = 9;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField10.setText(str);
       
     row = table1.getSelectedRow();   col = 10;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField11.setText(str);
         row = table1.getSelectedRow();  col = 11;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField12.setText(str);
   
        row = table1.getSelectedRow();  col = 12;
     str =String.valueOf(table1.getValueAt(row,col));
        jTextField13.setText(str);
        
        
        row = table1.getSelectedRow();  col = 13;
     str =String.valueOf(table1.getValueAt(row,col));
    
        jTextField14.setText(str);
        
        
        
        
        
    }//GEN-LAST:event_table1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER )
         {
             this.dispose();
         }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void table1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table1KeyReleased
        table1MouseClicked(null);
    }//GEN-LAST:event_table1KeyReleased

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
          
    }//GEN-LAST:event_jTextField7FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewissuereturndatehistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewissuereturndatehistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewissuereturndatehistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewissuereturndatehistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                viewissuereturndatehistory dialog = new viewissuereturndatehistory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel r;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
